version: '3'

services:

  doc_template:
    # image: mcr.microsoft.com/dotnet/aspnet:6.0
    build: .
    command: dotnet /app/DocTemplate.dll
    ports:
        - 8005:80
    volumes:
        - ./fonts:/fonts
        - ./files:/files

